# Generated by Django 4.1.7 on 2023-04-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0010_remove_product_description_remove_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='kartik@gmail.com', max_length=50)),
                ('password', models.CharField(default='fruits', max_length=50)),
            ],
        ),
    ]
