# Generated by Django 4.1.7 on 2023-05-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0013_brand_vendors_customer_agentimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminl',
            name='email',
        ),
        migrations.AddField(
            model_name='adminl',
            name='username',
            field=models.CharField(default='mr.pratik_m', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminl',
            name='password',
            field=models.CharField(default='passw', max_length=50),
        ),
    ]
