# Generated by Django 3.2.19 on 2023-05-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0017_auto_20230512_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='Admin-Dashboard/build/static/uploads/categ/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='Admin-Dashboard/build/static/uploads/customers/'),
        ),
        migrations.AlterField(
            model_name='delivpart',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='Admin-Dashboard/build/static/uploads/delivpar/'),
        ),
        migrations.AlterField(
            model_name='finmanager',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='Admin-Dashboard/build/static/uploads/finman/'),
        ),
        migrations.AlterField(
            model_name='invman',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='Admin-Dashboard/build/static/uploads/invman/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='Admin-Dashboard/build/static/uploads/products/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='Admin-Dashboard/build/static/uploads/subcateg/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='Admin-Dashboard/build/static/uploads/vendors/'),
        ),
    ]
