# Generated by Django 3.2.19 on 2023-05-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0021_auto_20230522_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivpart',
            name='orderId',
            field=models.ForeignKey(blank=True, default='abc', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminl.invman'),
        ),
        migrations.AlterField(
            model_name='invman',
            name='orderId',
            field=models.CharField(blank=True, default='abc', max_length=10, null=True),
        ),
    ]
