# Generated by Django 3.2.19 on 2023-05-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0025_auto_20230522_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivpart',
            name='orderId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminl.invman'),
        ),
        migrations.AlterField(
            model_name='invman',
            name='orderId',
            field=models.CharField(default='abc', max_length=10),
        ),
    ]
