# Generated by Django 3.2.19 on 2023-05-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0026_auto_20230522_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invman',
            name='orderId',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
