# Generated by Django 3.2.19 on 2023-05-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0027_alter_invman_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivpart',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='invman',
            name='orderId',
        ),
    ]
