# Generated by Django 3.2.19 on 2023-06-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0029_auto_20230522_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivpart',
            name='password',
            field=models.CharField(default='test1234', max_length=50),
        ),
        migrations.AddField(
            model_name='invman',
            name='password',
            field=models.CharField(default='test1234', max_length=50),
        ),
    ]
