# Generated by Django 3.2.19 on 2023-06-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0030_auto_20230601_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivpart',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='delivpart',
            name='password',
        ),
        migrations.RemoveField(
            model_name='invman',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='invman',
            name='password',
        ),
    ]
