# Generated by Django 3.2.19 on 2023-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0035_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='agentimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
