# Generated by Django 3.2.19 on 2023-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0036_alter_vendor_agentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='agentimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
